"""initial schema with amendments A1-A5

Revision ID: 9e46329c8419
Revises: 
Create Date: 2026-09-29 08:12:09.845790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '9e46329c8419'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before reference_asset.embedding is created. Amendment
    # A3 chose it, so it is part of the schema rather than an environment
    # prerequisite, and a fresh database must get it from the migration.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ref_table', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('total_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('price_verified_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ref_table IN ('generation', 'job', 'keyframe', 'voice_line')", name='ck_ref_table_vocabulary'),
    sa.CheckConstraint('total_usd >= 0', name='ck_cost_ledger_total_not_negative'),
    sa.CheckConstraint('units >= 0', name='ck_cost_ledger_units_not_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_ledger_created', 'cost_ledger', ['created_at'], unique=False)
    op.create_index('ix_cost_ledger_ref', 'cost_ledger', ['ref_table', 'ref_id'], unique=False)
    op.create_table('decision_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_log_key', 'decision_log', ['key'], unique=False)
    op.create_table('persona',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('active_lora_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'draft', 'retired')", name='ck_status_vocabulary'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content_piece',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='brief', nullable=False),
    sa.Column('target_platforms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('brief_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('abandoned', 'assembled', 'brief', 'generating', 'published', 'review', 'shotlist')", name='ck_status_vocabulary'),
    sa.CheckConstraint('render_completed_at IS NULL OR brief_started_at IS NULL OR render_completed_at >= brief_started_at', name='ck_content_piece_timestamps_ordered'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lora_version',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('base_model', sa.String(length=256), nullable=False),
    sa.Column('base_model_licence', sa.Text(), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('eval_score', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_asset',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=128), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=True),
    sa.Column('is_master', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('body', 'face', 'lighting', 'outfit')", name='ck_kind_vocabulary'),
    sa.CheckConstraint('(embedding IS NULL) OR (embedding_model IS NOT NULL AND embedding_model_version IS NOT NULL)', name='ck_reference_asset_embedding_has_provenance'),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reference_asset_persona_master', 'reference_asset', ['persona_id', 'is_master'], unique=False)
    op.create_table('render',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content_piece_id', sa.UUID(), nullable=False),
    sa.Column('edl_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('aspect', sa.String(length=8), nullable=False),
    sa.Column('disclosure_applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('c2pa_manifest_key', sa.String(length=512), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('identity_score_min', sa.Double(), nullable=True),
    sa.Column('identity_score_mean', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("aspect IN ('16:9', '1:1', '9:16')", name='ck_aspect_vocabulary'),
    sa.CheckConstraint('c2pa_manifest_key IS NULL OR disclosure_applied', name='ck_render_manifest_requires_disclosure'),
    sa.CheckConstraint('identity_score_mean IS NULL OR (identity_score_mean >= 0 AND identity_score_mean <= 1)', name='ck_identity_score_mean_unit_range'),
    sa.CheckConstraint('identity_score_min IS NULL OR (identity_score_min >= 0 AND identity_score_min <= 1)', name='ck_identity_score_min_unit_range'),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'disclosure_applied', name='uq_render_id_disclosure')
    )
    op.create_table('shot',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content_piece_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_s', sa.Double(), nullable=False),
    sa.Column('camera', sa.Text(), nullable=True),
    sa.Column('lighting', sa.Text(), nullable=True),
    sa.Column('dialogue', sa.Text(), nullable=True),
    sa.Column('shot_type', sa.String(length=16), nullable=False),
    sa.CheckConstraint("shot_type IN ('broll', 'face')", name='ck_shot_type_vocabulary'),
    sa.CheckConstraint('duration_s > 0', name='ck_shot_duration_positive'),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_piece.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_piece_id', 'order_index', name='uq_shot_order')
    )
    op.create_table('keyframe',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('shot_id', sa.UUID(), nullable=False),
    sa.Column('lora_version_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('identity_score', sa.Double(), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('identity_score IS NULL OR (identity_score >= 0 AND identity_score <= 1)', name='ck_identity_score_unit_range'),
    sa.ForeignKeyConstraint(['lora_version_id'], ['lora_version.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shot_id'], ['shot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('render_id', sa.Uuid(), nullable=False),
    sa.Column('disclosure_applied', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('account', sa.String(length=128), nullable=False),
    sa.Column('ai_label_set', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ai_label_set', name='ck_publication_ai_label_set'),
    sa.CheckConstraint('disclosure_applied', name='ck_publication_disclosure_applied'),
    sa.CheckConstraint('length(trim(approved_by)) > 0', name='ck_publication_approver_named'),
    sa.ForeignKeyConstraint(['render_id', 'disclosure_applied'], ['render.id', 'render.disclosure_applied'], name='fk_publication_render_disclosed', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'url', name='uq_publication_platform_url')
    )
    op.create_table('voice_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('shot_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('voice_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_usd >= 0', name='ck_voice_line_cost_not_negative'),
    sa.ForeignKeyConstraint(['shot_id'], ['shot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('shot_id', sa.UUID(), nullable=False),
    sa.Column('keyframe_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('duration_s', sa.Double(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('identity_score_min', sa.Double(), nullable=True),
    sa.Column('identity_score_mean', sa.Double(), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('auto_rejected', 'failed', 'generating', 'queued', 'ready', 'scored')", name='ck_status_vocabulary'),
    sa.CheckConstraint('cost_usd >= 0', name='ck_generation_cost_not_negative'),
    sa.CheckConstraint('identity_score_mean IS NULL OR (identity_score_mean >= 0 AND identity_score_mean <= 1)', name='ck_identity_score_mean_unit_range'),
    sa.CheckConstraint('identity_score_min IS NULL OR (identity_score_min >= 0 AND identity_score_min <= 1)', name='ck_identity_score_min_unit_range'),
    sa.CheckConstraint('identity_score_min IS NULL OR identity_score_mean IS NULL OR identity_score_min <= identity_score_mean', name='ck_generation_min_not_above_mean'),
    sa.ForeignKeyConstraint(['keyframe_id'], ['keyframe.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['shot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_snapshot',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('watch_time_s', sa.Integer(), nullable=True),
    sa.Column('retention_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('followers_delta', sa.Integer(), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'captured_at', name='uq_metric_snapshot_capture')
    )
    op.create_table('job',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_job_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='submitted', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('cancelled', 'failed', 'running', 'submitted', 'succeeded', 'timed_out')", name='ck_status_vocabulary'),
    sa.CheckConstraint("status IN ('submitted', 'running') OR cost_usd IS NOT NULL", name='ck_job_finished_has_cost'),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= submitted_at', name='ck_job_completed_after_submitted'),
    sa.CheckConstraint('cost_usd >= 0', name='ck_job_cost_not_negative'),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_provider_job_id', 'job', ['provider', 'provider_job_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_tags', sa.Text(), nullable=True),
    sa.Column('time_spent_s', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('accept', 'reject')", name='ck_decision_vocabulary'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_review_rating_range'),
    sa.CheckConstraint('time_spent_s IS NULL OR time_spent_s >= 0', name='ck_review_time_not_negative'),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # The vector extension is deliberately NOT dropped. Another schema in the same
    # database may be using it, and downgrading this migration is not a licence to
    # break them.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_index('ix_job_provider_job_id', table_name='job')
    op.drop_table('job')
    op.drop_table('metric_snapshot')
    op.drop_table('generation')
    op.drop_table('voice_line')
    op.drop_table('publication')
    op.drop_table('keyframe')
    op.drop_table('shot')
    op.drop_table('render')
    op.drop_index('ix_reference_asset_persona_master', table_name='reference_asset')
    op.drop_table('reference_asset')
    op.drop_table('lora_version')
    op.drop_table('content_piece')
    op.drop_table('persona')
    op.drop_index('ix_decision_log_key', table_name='decision_log')
    op.drop_table('decision_log')
    op.drop_index('ix_cost_ledger_ref', table_name='cost_ledger')
    op.drop_index('ix_cost_ledger_created', table_name='cost_ledger')
    op.drop_table('cost_ledger')
    # ### end Alembic commands ###
