"""Declarative base and the column types used across the schema.

Three choices worth stating once here rather than repeating at every column.

**Money is `Numeric`, never float.** A take costs $0.0125 per second and the
ledger has to reconcile against a real invoice. Six decimal places because the
unit prices themselves run to four.

**Enumerations are `String` plus a CHECK, not a native Postgres enum.** A native
enum needs a migration to add a value and cannot have one removed at all, and
this project's vocabularies are still moving — the failure-tag list was rewritten
once already. A CHECK is also directly testable, which is what task 0.3's
"constraints tested" asks for.

**Identifiers are UUIDs generated by the database.** Rows are referenced from
object-storage keys and from provider job ids, so an identifier that is unique
without a round trip to the sequence is worth the extra bytes.
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal
from typing import Annotated, Any

from sqlalchemy import CheckConstraint, DateTime, Numeric, String, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, mapped_column, registry

#: A JSONB column. Named rather than bare `dict` so the annotation carries its
#: value type, and registered below so `Mapped[JsonDict]` resolves to JSONB.
JsonDict = dict[str, Any]


class Base(DeclarativeBase):
    registry = registry(
        type_annotation_map={
            dt.datetime: DateTime(timezone=True),
            Decimal: Numeric(12, 6),
            JsonDict: JSONB,
        }
    )


#: Primary key. `gen_random_uuid()` is built into Postgres 13+, so no extension.
PrimaryKey = Annotated[
    uuid.UUID,
    mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    ),
]

#: Set by the database, so the value does not depend on the app's clock.
CreatedAt = Annotated[
    dt.datetime,
    mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now()),
]

#: USD. See the note on Numeric above.
Money = Annotated[Decimal, mapped_column(Numeric(12, 6), nullable=False)]
OptionalMoney = Annotated[Decimal | None, mapped_column(Numeric(12, 6), nullable=True)]

#: A key into object storage. The database stores keys, never blobs
#: (BUILD_PLAN Section 3).
StorageKey = Annotated[str, mapped_column(String(512), nullable=False)]
OptionalStorageKey = Annotated[str | None, mapped_column(String(512), nullable=True)]

#: A cosine similarity, or a rate expressed as one. Scores outside 0..1 mean the
#: scorer changed or the vector was not normalised, and both are worth catching
#: at write time rather than discovering in a report.
Score = Annotated[float | None, mapped_column(nullable=True)]


def one_of(column: str, *allowed: str) -> CheckConstraint:
    """A CHECK restricting a column to a fixed vocabulary.

    Named after the column so a violation in a log line says which one.
    """
    values = ", ".join(f"'{value}'" for value in sorted(allowed))
    return CheckConstraint(f"{column} IN ({values})", name=f"ck_{column}_vocabulary")


def score_in_unit_range(column: str) -> CheckConstraint:
    return CheckConstraint(
        f"{column} IS NULL OR ({column} >= 0 AND {column} <= 1)",
        name=f"ck_{column}_unit_range",
    )
